# Generated by Django 5.0.6 on 2024-07-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_books_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='books/media/uploads'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
