# Generated by Django 5.0.6 on 2024-07-06 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_account'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user.useraccount'),
        ),
    ]
