# Generated by Django 5.0.6 on 2024-07-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='balance_after_transaction',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
