# Generated by Django 5.0.6 on 2024-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactions_balance_after_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
